img=cv2.imread('/content/bird.jpg')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
_ ,thresh = cv2.threshold(gray,127,255,0)
contours,_ = cv2.findContours(thresh,cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(img,contours,-1,(0,255,0),2)
plt.imshow(img)
